language: java
before_script:
- echo "Starting build"
script:
- mvn clean package
deploy:
  provider: heroku
  api_key:
    secure: "VSkjrhULYxzzrimdoMb0M4uQO68DyNCL3zWrgJiRfttBMJYT3swUCbMgNg4f8RNf4x>
  app:
    master: pi222team13
    pi222team13DanilovBranch: danilov-branch
    KolesovaBranch: kolesova-branch
    YusupovaBranch: yusupova-branch
